### ISSUE TITLE
Unable to load Plugin (Euroscope Plugin Menu)

### ISSUE THREAD

**Issue by danlovett** [GoodCrossing/StripMaker#3]
**Unable to actually load and test this plugin.**
'Failed to load DLL Plugin' --> https://i.imgur.com/cP8ieyg.png

**Comment by GoodCrossing** [comment]
Hi! Where is your ES exe located?

**Comment by danlovett** [comment]
Hello, 'C:\Program Files (x86)\EuroScope'

**Comment by GoodCrossing** [comment]
Ahh, that's the problem then. I've got mine is Documents so didn't have that issue. If you copy everything to the Documents folder it should work, but I'll try to fix it so you don't need to do that. I'll update this ticket when it's done.

**Comment by danlovett** [comment]
Okay. I will try moving the plugin to where my ES exe is for now to see if this temporarily fixes this.

**Comment by GoodCrossing** [comment]
Huh - I was just writing a response saying the only fix is to have the exe in documents, but if that doesn't work, that's weird. I'm currently on KK AIR, but after I come off, I'll try to debug this further.

**Comment by GoodCrossing** [comment]
hi, can you try to delete **both** DLLs (stripmaker and fmt) and then extracting this DLL in documents/program files? Does it load in any of the locations?
[stripmaker_issue3.zip](https://github.com/GoodCrossing/StripMaker/files/5752617/stripmaker_issue3.zip)

**Comment by danlovett** [comment]
Hello, both where deleted. I tried using es exe from documents and program files, routing to the dll, in both Euroscope/ and UK/. No luck. https://i.imgur.com/IhqCjrW.png

**Comment by GoodCrossing** [comment]
Hmmm... Let's see how far it gets. I've added some error windows at different points of the plugin startup, let me know if you see any of them.
[StripMaker-issue3-2.zip](https://github.com/GoodCrossing/StripMaker/files/5752687/StripMaker-issue3-2.zip)

**Comment by danlovett** [comment]
https://i.imgur.com/ykV4WPg.png still getting this. Just confirm what files i should have in the folder - just that one .dll file?

**Comment by GoodCrossing** [comment]
OK, I think this one should do it. If it does load, add the StripMaker TAG items to your list and try to print a strip. If it crashes, try to unload UKCP and let me know. Thanks for bearing with me :)
[StripMaker-issue3-4withabitofgoodluck.zip](https://github.com/GoodCrossing/StripMaker/files/5752878/StripMaker-issue3-4withabitofgoodluck.zip)

**Comment by danlovett** [comment]
Sam, It worked! And do not worry, I'm trying to create an SMR file at tho mo - not exactly going to plan. Loaded perfectly. There's now a new issue but ill create a new tab so people in the future can find the issue and fix 👍

**Comment by GoodCrossing** [comment]
Just to clarify a bit - this was a problem with the build. I had released my debug build so it included debug features, however, it won't load unless you have Visual Studio installed. The first person that tested the plugin happened to have VS installed **and** ES installed in Documents, so that acted as a red herring that made me think it was something to do with ES :) next build will be done properly I guess
