### ISSUE TITLE
On Print (Dep List Item), ES Crashes.

### ISSUE THREAD

**Issue by danlovett** [GoodCrossing/StripMaker#4]
Hello,

Everything is set up and is ready to be used. Plugin Loaded, items in dep list all set up...
When I go to press print, ES crashes with the log:
```
'EuroScope caused an Access Violation (0xc0000005) 
in module StripMaker.dll at 0023:62982cc9.'
```

Help Please, Merci.

**Comment by GoodCrossing** [comment]
Just happened to be working on this now. I'm pretty sure I know where the problem is, as I'm able to reproduce from my side. I'll look into it and make an update.

**Comment by GoodCrossing** [comment]
Should be fixed with this last commit. I had removed the loadSettings() function while diagnosing issue #3 , and I forgot to add it back again. Settings weren't being loaded. D'oh! Test it out and feel free to close the issue if it works.

Here's the compiled plug-in:
[StripMaker-issue4-fix.zip](https://github.com/GoodCrossing/StripMaker/files/5753041/StripMaker-issue4-fix.zip)

**Comment by danlovett** [comment]
Doesn't work. 2 errors are now thrown at me.
https://i.imgur.com/sV2CF5i.png
https://i.imgur.com/APcoSAf.png

Happy to help!

**Comment by GoodCrossing** [comment]
Hi,

Can you confirm that the StripMaker folder containing the templates folder is in the same directory as the dll? So, you should see stripmaker.dll **and** a folder named StripMaker. 

Also, when is the second error occurring?

**Comment by danlovett** [comment]
Hello Affirm --> https://i.imgur.com/QaqfmB6.png

The second error occurs after the first one (The abort message shows first - causing ES not to respond - then the loading error occurs straight after aborting the first error).

**Comment by GoodCrossing** [comment]
I see the problem. The plug-in is looking for a folder next to it named StripMaker, but me basing inexperienced in DLL development, I didn't realize the 'it' in next to it was the EuroScope exe. Moving the whole StripMaker folder to Program Files will fix it for now, but when I come back home I'll change the code so you can put the StripMaker folder to your preferred directory.

**Comment by danlovett** [comment]
Aye all working now, thanks for the help and making a useful and enjoyable plugin aha.
